# ~/.bashrc

# Exit early for non-interactive shells.
[[ $- != *i* ]] && return

# History
export HISTCONTROL=ignoreboth
export HISTSIZE=10000
export HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Better history search (up/down arrow searches by prefix)
is_interactive_tty=0
if [[ $- == *i* ]] && [[ -t 0 ]] && [[ -t 1 ]]; then
  is_interactive_tty=1
fi

if [[ $is_interactive_tty -eq 1 ]]; then
  bind '"\e[A": history-search-backward'
  bind '"\e[B": history-search-forward'
fi

# Prompt
ESC_RESET="\[$(tput sgr0)\]"
ESC_BLUE_FG="\[$(tput setaf 4)\]"
PS_DIR="${ESC_BLUE_FG}\W${ESC_RESET}"
PS_INDICATOR="\$"
export PS1="${PS_DIR} ${PS_INDICATOR} "

# Environment
export EDITOR="nvim"
export LEDGER_FILE="/home/seryiza/code/sfinances/main.journal"

# Aliases: ls
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Aliases: search
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'

# Aliases: git
alias gst="git status"
alias gs="git status"
alias ga="git add"
alias gd="git diff"
alias gdca="git diff --staged"
alias gup="git pull --rebase"
alias gp="git push"
alias gr="git restore"
alias grs="git restore --staged"
alias gco="git checkout"
alias gcmsg="git commit -m"
alias gcl="git clone"
alias glo="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gsu="git submodule update"
alias ghpr="gh pr create -a @me && gh pr merge --auto --delete-branch --rebase"

# Aliases: nix
alias vinix="sudo $EDITOR /home/seryiza/code/my-dev-env/nixos/configuration.nix"
alias nr="sudo nixos-rebuild"
alias nrs="sudo nixos-rebuild switch --flake /home/seryiza/code/my-dev-env#yuri-alpha"
alias nrr="nix flake update --flake /home/seryiza/code/my-dev-env && sudo nixos-rebuild switch --flake /home/seryiza/code/my-dev-env#yuri-alpha"
alias ncg="sudo nix-collect-garbage --delete-older-than 7d"

alias dc="docker-compose"
alias docker-compose="docker compose"
alias e="emacs -nw"
alias n="nvim"
alias m="make"

if [[ "$INSIDE_EMACS" ]]; then
    export PAGER=less # Emacs overrides PAGER on startup. Revert it back.
fi
