# Colors
color_grey='#AAAAAA'
color_black='#000000'

# Common options
set -g base-index 1
set -g mouse on
set -sg escape-time 10
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Change prefix to (ctrl + j)
set-option -g prefix C-j
unbind C-b
bind C-j send-prefix

# Bindings
bind t source-file ~/.tmux.conf
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Status options
set -g status-justify centre
set -g status-left ''
set -g status-right ''
set -g status-style 'none'
set -g window-status-style fg=$color_grey
set -g window-status-format " #I: #W "
set -g window-status-current-format " #I: #W "
set -g window-status-current-style fg=$color_black
