- name: Install asdf
  command:
    cmd: '{{yay}} asdf-vm'
    creates: '/opt/asdf-vm/asdf.sh'

- name: Install plugins
  loop:
    - {name: "java", git: "https://github.com/halcyon/asdf-java.git"}
  command:
    cmd: "{{asdf}} plugin add {{item.name}} {{item.git}}"
    creates: "{{asdf_home}}/plugins/{{item.name}}"

