- name: install emacs
  command:
    cmd: "{{yay}} emacs"
    creates: "{{usr_bin}}/emacs"

- name: install spacemacs
  git:
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: "~/.emacs.d"
    version: "develop"

- name: add .spacemacs
  loop:
    - 'init.lua'
    - 'lua'
  file:
    path: '~/.config/nvim/{{ item }}'
    src: '{{ role_path }}/files/{{ item }}'
    state: link
