- name: Install autojump
  command:
    creates: "{{usr_bin}}/autojump"
    cmd: "{{yay}} autojump"

- name: Setup config
  loop:
    - '.bashrc'
    - '.profile'
  file:
    path: '~/{{ item }}'
    src: '{{ role_path }}/files/{{ item }}'
    force: true
    state: link
