- name: Install Kitty
  command:
    creates: '{{usr_bin}}/kitty'
    cmd: '{{yay}} kitty'

- name: Create config directory
  file:
    path: '~/.config/kitty'
    state: directory

- name: Setup config
  file:
    path: '~/.config/kitty/kitty.conf'
    src: '{{ role_path }}/files/kitty.conf'
    state: link
