- name: Install NeoVim
  command:
    creates: '{{usr_bin}}/nvim'
    cmd: '{{yay}} neovim'

- name: Install Packer
  command:
    creates: '{{usr_share}}/nvim/site/pack/packer'
    cmd: '{{yay}} nvim-packer-git'

- name: Update nvim packages
  command:
    cmd: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
  register: "nvim_result"
  changed_when: "nvim_result.rc != 0"

- name: Create config directory
  file:
    path: '~/.config/nvim'
    state: directory

- name: Setup config (create links)
  loop:
    - 'init.lua'
    - 'lua'
  file:
    path: '~/.config/nvim/{{ item }}'
    src: '{{ role_path }}/files/{{ item }}'
    state: link
