- name: Install NeoVim
  command:
    creates: '{{brew_bin_dir}}/nvim'
    cmd: '{{brew}} install neovim'

- name: Create config directory
  file:
    path: '~/.config/nvim'
    state: directory

- name: Setup config (create links)
  loop:
    - 'init.lua'
    - 'lua'
  file:
    path: '~/.config/nvim/{{ item }}'
    src: '{{ role_path }}/files/{{ item }}'
    state: link
