- name: Install Tmux
  command:
    creates: '{{usr_bin}}/tmux'
    cmd: '{{yay}} tmux'

- name: Setup config
  file:
    path: '~/.tmux.conf'
    src: '{{role_path}}/files/.tmux.conf'
    state: link
