- hosts: all
  vars:
    brew_bin_dir: /home/linuxbrew/.linuxbrew/bin
    brew: '{{brew_bin_dir}}/brew'

  roles:
    - chrome

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: true
        upgrade: true

    - name: Install Homebrew
      shell:
        creates: '{{brew_bin_dir}}/brew'
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install NeoVim
      command:
        creates: '{{brew_bin_dir}}/nvim'
        cmd: '{{brew}} install neovim'
