- hosts: all
  vars:
    brew_bin_dir: /home/linuxbrew/.linuxbrew/bin
    brew: '{{brew_bin_dir}}/brew'
    usr_bin: /usr/bin
    usr_share: /usr/share
    yay: yay -Syq --needed --noconfirm
    asdf: /opt/asdf-vm/bin/asdf
    asdf_home: "~/.asdf"

  roles:
    # Package managers
    - asdf

    # Core utils
    - bash
    - kitty

    # Development
    - neovim
    - tmux

    # Other
    - chrome
