- hosts: all
  vars:
    brew_bin_dir: /home/linuxbrew/.linuxbrew/bin
    brew: '{{brew_bin_dir}}/brew'

  roles:
    - homebrew
    - chrome
    - neovim

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: true
        upgrade: true
    
