- name: Install Starship
  command:
    creates: '{{brew_bin_dir}}/starship'
    cmd: '{{brew}} install starship'

- name: Create config directory
  file:
    path: '~/.config'
    state: directory

- name: Setup config
  file:
    path: '~/.config/starship.toml'
    src: '{{ role_path }}/files/starship.toml'
    state: link
